app/blueprints/skill/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, validators

class SessionForm(FlaskForm):
    topic   = StringField()
    entry = IntegerField(validators=[validators.optional()])
    entry_figure = IntegerField(validators=[validators.optional()])
    recap = IntegerField(validators=[validators.optional()])
    zettel = IntegerField(validators=[validators.optional()])
    zettel_figure = IntegerField(validators=[validators.optional()])
    konzeptzettel = IntegerField(validators=[validators.optional()])
    konzeptzettel_appendix = IntegerField(validators=[validators.optional()])
    zettel_digitalised = IntegerField(validators=[validators.optional()])
    for_db = IntegerField(validators=[validators.optional()])
    for_db_selfmade = IntegerField(validators=[validators.optional()])
    finished_project = IntegerField(validators=[validators.optional()])
    framework_selfmade = IntegerField(validators=[validators.optional()])
    complete_routine = IntegerField(validators=[validators.optional()])
    routine_part = IntegerField(validators=[validators.optional()])



class SkillForm(FlaskForm):
    skill_name = StringField('new skill name')

app/blueprints/skill/routes.py
from flask import Blueprint, render_template, url_for, request, redirect, url_for, session
from .forms import SessionForm, SkillForm
import json
from datetime import date


skill_bp = Blueprint(
    'skill_bp', __name__, url_prefix='/skills',
    template_folder='templates', static_folder='static'
)


from .errorhandlers import *
from .helper_functions import (
     load_skills_from, dump_skills_to, load_xp_rewards, calculate_lv
)


@skill_bp.route('/', methods=['POST', 'GET'])
@skill_bp.route('/overview', methods=['POST', 'GET'])
def index():
    form = SkillForm(request.form)
    skills = load_skills_from(path='json/skills.json')
    skill_sessions = []

    # load all sessions from all skills
    for skill in skills.values():
        for skill_session in skill['sessions']:
            skill_sessions.append(skill_session)

    # process form and update skills
    if request.method == 'POST' and form.validate():
        # init new skill
        new_skill_name = form.skill_name.data
        new_skill = {'name':new_skill_name, 'xp':0, 'lv':'1', 'sessions':[]}
        # add to skills and save as json
        skills[new_skill_name] = new_skill
        dump_skills_to(path='json/skills.json', skills=skills)

        return redirect(url_for('skill_bp.index'))

    return render_template('index.html',
        form=form,
        skills=skills,
        skill_sessions=skill_sessions
    )



@skill_bp.route('/<skill_name>', methods=['POST', 'GET'])
def skill_page(skill_name):
    form = SessionForm(request.form)
    skills = load_skills_from(path='json/skills.json')
    skill = skills[skill_name]

    if request.method == 'POST' and form.validate():
        xp_rewards = load_xp_rewards()
        new_session = {
             'date':str(date.today()),
             'xp':0,
             'mediums':[]
        }
        populated_medium_fields = {}

        # filter medium fields for later use
        # use topic field as the session's topic
        for field in form:
            if field.widget.input_type != 'hidden':
                if field.name != 'topic' and field.data:
                    populated_medium_fields[field.name] = field.data
                elif field.name == 'topic':
                    new_session['topic'] = field.data

        # process the session's mediums
        for medium_name, medium_value in populated_medium_fields.items():
            new_medium = {
                'medium': medium_name,
                'amount': medium_value,
                'xp': xp_rewards[medium_name] * medium_value
            }
            new_session['mediums'].append(new_medium)
            new_session['xp'] += new_medium['xp']

        # append session to skill and update xp/lv of the skill
        skill['sessions'].append(new_session)
        skill['xp'] += new_session['xp']
        skill['lv'] = calculate_lv(skill['xp'])

        dump_skills_to(path='json/skills.json', skills=skills)
        return redirect(url_for('skill_bp.skill_page', skill_name=skill_name))

    return render_template('skill.html',
        skill=skill,
        skill_name=skill_name,
        skill_sessions=skill['sessions'],
        form=form
    )



@skill_bp.route('/<skill>/reward')
def reward_page(skill):
    return render_template('reward.html', skill=skill)



@skill_bp.route('xp-rewards')
def xp_rewards():
    xp_dict = load_xp_rewards()
    return render_template('xp-rewards.html', xp_dict=xp_dict)

app/blueprints/skill/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Skill</title>
        {% block imports %}

        {% endblock imports %}
    </head>
    <body>
        {% include 'navbar.html' %}

        {% block content  %}

        {% endblock content  %}
    </body>
</html>

app/blueprints/skill/templates/index.html
{% extends 'base.html' %}

{% block imports %}

<link rel='stylesheet'  href="{{ url_for('.static', filename='css/skills/index.css') }}">

{% endblock imports %}

{% block content %}

<div class="skills-grid">
    <!-- SESSIONS LISTING -->
    <div class="history box">
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>XP</th>
                    <th>Summary</th>
                </tr>
            </thead>
            <tbody>
            {% for session in skill_sessions | sort(attribute='date', reverse=True) %}
                <tr>
                    <td>{{session.date}}</td>
                    <td>{{session.xp}}</td>
                    <td>{{session.topic}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>




    <!-- SKILLS LISTING -->
    <div class="skills-card-grid">
        {% for skill_name, skill_object in skills.items() %}
        <a class='skill-card' href={{ url_for('skill_bp.skill_page', skill_name=skill_name) }}>
            <p class="skill-name"> {{skill_object.name}} </p>
            <p class="skill-level"> Lv {{ skill_object.lv }} </p>
            <p class="skill-xp"> {{ skill_object.xp }} xp </p>
        </a>
        {% endfor %}
    </div>
</div>
















<div class="button-grid">
    <!-- FORM TO ADD SKILLS -->
    <form class="skill-form" action='{{ url_for('skill_bp.index') }}' method="post">
        {{ form.csrf_token }}
        {% for field in form if field.id != 'csrf_token' %}
            {{ field.label }}
            <br>
            {{ field }}
            <br>
        {% endfor %}
        <input type="submit" value="add skill">
    </form>

    <a href={{ url_for('skill_bp.xp_rewards') }}>Show XP Table</a>
</div>

{% endblock content %}

app/blueprints/skill/templates/navbar.html
<nav>
    <div class="nav-items">
        <a href={{ url_for('skill_bp.index') }}>
            XP
        </a>

        <a href={{ url_for('skill_bp.construction_page') }}>
            ZK
        </a>

        <a href={{ url_for('skill_bp.construction_page') }}>
            QPPP
        </a>

        <a href={{ url_for('skill_bp.construction_page') }}>
            QR
        </a>
    </div>
    <hr class='nav-hr'>
</nav>

app/blueprints/skill/templates/reward.html
{% extends 'base.html' %}

{% block content %}

    <div class="reward-popup">
        <img src="" alt="">
        <div class="reward-notification">
            <h1>CONGRATULATIONS</h1>
            <h2>NOW PICK A REWARD!</h2>
        </div>

        <div class="reward-listing">
            <a href={{ url_for('skill_bp.index')}} class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
            <a href="#" class='reward-link'>reward</a>
        </div>
    </div>

{% endblock content %}

app/blueprints/skill/templates/skill.html
{% extends 'base.html' %}

{% block content %}
    <!-- SKILL INFO -->
    <h2>{{skill.name}}</h2>
    <p>Lv {{skill.lv}} - XP {{skill.xp}}</p>
    <hr>

    <!-- SESSIONS LISTING -->
    <div class="history box">
        <table>
            <tr>
                <th>Date</th>
                <th>XP</th>
                <th>Summary</th>
            </tr>
            {% for session in skill_sessions | sort(attribute='date', reverse=True) %}
                <tr>
                    <td>{{session.date}}</td>
                    <td>{{session.xp}}</td>
                    <td>{{session.topic}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <hr class="form-break">

    <!-- SESSION FORM -->
    <h3>Add a session and earn some XP</h3>
    <form class="session-form" action={{ url_for('skill_bp.skill_page', skill_name=skill_name) }} method="post">
            {{ form.csrf_token }}
            {% for field in form if field.widget.input_type != 'hidden' %}
                {{ field.label }}
                {{ field }}
                <br>
            {% endfor %}
            <input type="submit"  value="get that xp!">
    </form>

{% endblock content %}

app/blueprints/skill/templates/xp-rewards.html
{% extends 'base.html' %}

{% block content %}
<table>
    <tr>
        <th>Medium</th>
        <th>XP</th>
    </tr>
    {% for medium, xp in xp_dict.items() %}
    <tr>
        <td>{{medium}}</td>
        <td>{{xp}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

app/blueprints/skill/templates/zk.html
{% extends 'base.html' %}

{% block content %}

    <h1>Be patient</h1>
    <h3>This site is still under construction!</h3>

{% endblock content %}